### ISSUE TITLE
Jobs (reborn)

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Depenizen#127]
Hi guys,

Is possible to repair support for old jobs plugin to "reborn" job plugin please ?

https://www.spigotmc.org/resources/jobs-reborn.4216/

Thanks !

Errors:   
```
 Caused by: java.lang.NoSuchMethodError: com.gamingmesh.jobs.PlayerManager.getJobsPlayerOffline(Lorg/bukkit/OfflinePlayer;)Lcom/gamingmesh/jobs/container/JobsPlayer;
at com.denizenscript.depenizen.bukkit.extensions.jobs.JobsPlayerExtension.<init>(JobsPlayerExtension.java:29)
at com.denizenscript.depenizen.bukkit.extensions.jobs.JobsPlayerExtension.getFrom(JobsPlayerExtension.java:24)

````

**Comment by Morphan1** [comment]
Thanks for your report! It has been added to the latest build
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/

**Comment by Oruss7** [comment]
Thank you Morphan1, so quick ^^
