### ISSUE TITLE
Residence support: up to latest

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Depenizen#134]
Please update support of residence, breaking changes are made... 

```
[00:10:55] [pool-244-thread-1/INFO]:  ERROR! Internal exception was thrown!
[00:10:55] [pool-244-thread-1/WARN]: java.lang.reflect.InvocationTargetException
[00:10:55] [pool-244-thread-1/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:10:55] [pool-244-thread-1/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:10:55] [pool-244-thread-1/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:10:55] [pool-244-thread-1/WARN]:     at java.lang.reflect.Method.invoke(Method.java:497)
[00:10:55] [pool-244-thread-1/WARN]:     at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[00:10:55] [pool-244-thread-1/WARN]:     at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2130)
[00:10:55] [pool-244-thread-1/WARN]:     at net.aufdemrand.denizen.tags.core.PlayerTags.playerTags(PlayerTags.java:90)
[00:10:55] [pool-244-thread-1/WARN]:     at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source)
[00:10:55] [pool-244-thread-1/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:10:55] [pool-244-thread-1/WARN]:     at java.lang.reflect.Method.invoke(Method.java:497)
[00:10:55] [pool-244-thread-1/WARN]:     at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[00:10:55] [pool-244-thread-1/WARN]:     at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[00:10:55] [pool-244-thread-1/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:10:55] [pool-244-thread-1/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:10:55] [pool-244-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:10:55] [pool-244-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:10:55] [pool-244-thread-1/WARN]:     at java.lang.Thread.run(Thread.java:745)
[00:10:55] [pool-244-thread-1/WARN]: Caused by: java.lang.IncompatibleClassChangeError: Expected static method com.bekvon.bukkit.residence.Residence.getPlayerManagerAPI()Lcom/bekvon/bukkit/residence/api/ResidencePlayerInterface;
[00:10:55] [pool-244-thread-1/WARN]:     at com.denizenscript.depenizen.bukkit.extensions.residence.ResidencePlayerExtension.<init>(ResidencePlayerExtension.java:30)
[00:10:55] [pool-244-thread-1/WARN]:     at com.denizenscript.depenizen.bukkit.extensions.residence.ResidencePlayerExtension.getFrom(ResidencePlayerExtension.java:25)
[00:10:55] [pool-244-thread-1/WARN]:     ... 17 more
```

**Comment by Oruss7** [comment]
I use 4.5.13.2

**Comment by Oruss7** [comment]
Done https://github.com/DenizenScript/Depenizen/commit/77e196aa9a8d7e52ac6affd6788657e6374d7771
