### ISSUE TITLE
Internal exception error

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Depenizen#162]
with ASkyBlock 3.0.6.8
denizen version: 1.0.2-SNAPSHOT (build 193), core version: 1.15 (Build 90)
depenizen version: 1.0.0 (build 382)

[14:31:55 INFO]: +- Executing dCommand: FLAG/p@test ---------+
[14:31:55 INFO]:  ERROR! Internal exception was thrown!
[14:31:55 WARN]: java.lang.reflect.InvocationTargetException
[14:31:55 WARN]:        at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source)
[14:31:55 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:31:55 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:31:55 WARN]:        at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[14:31:55 WARN]:        at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2159)
[14:31:55 WARN]:        at net.aufdemrand.denizen.tags.core.PlayerTags.playerTags(PlayerTags.java:90)
[14:31:55 WARN]:        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
[14:31:55 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:31:55 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:31:55 WARN]:        at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[14:31:55 WARN]:        at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[14:31:55 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:31:55 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:31:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:31:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:31:55 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:31:55 WARN]: Caused by: java.lang.NullPointerException
[14:31:55 WARN]:        at com.wasteofplastic.askyblock.ASkyBlockAPI.getIslandOwnedBy(ASkyBlockAPI.java:416)
[14:31:55 WARN]:        at com.denizenscript.depenizen.bukkit.extensions.askyblock.ASkyBlockPlayerExtension.<init>(ASkyBlockPlayerExtension.java:32)
[14:31:55 WARN]:        at com.denizenscript.depenizen.bukkit.extensions.askyblock.ASkyBlockPlayerExtension.getFrom(ASkyBlockPlayerExtension.java:26)
[14:31:55 WARN]:        ... 16 more
[14:31:55 INFO]:  Filled tag <player> with

on player right clicks player:
      - flag player "playertrigger:<context.entity>"

**Comment by wolfwork** [comment]
when target player dosen not have island

**Comment by Fortifier42** [comment]
This is an invalid error, your debug clearly shows you tried to execute `- flag p@test` followed by incomplete debug. Show full debug with the inbuilt debug haste service please.

**Comment by mcmonkey4eva** [comment]
How'd you get username `test` to be considered valid?

Hacked client is my guess.

**Comment by wolfwork** [comment]
your right mcmonkey

**Comment by Fortifier42** [comment]
We provide no support for hacked servers and clients.

**Comment by wolfwork** [comment]
I only use that for testing
