### ISSUE TITLE
mcMMO hook failure

### ISSUE THREAD

**Issue by SXRWahrheit** [DenizenScript/Depenizen#165]
mcMMO build 196

```
[10:28:49] [Server thread/WARN]: [Denizen] Task #112 for Denizen v1.0.2-SNAPSHOT (build 202) generated an exception
java.lang.NoSuchMethodError: com.gmail.nossr50.events.experience.McMMOPlayerLevelChangeEvent.getHandlerList()Lorg/bukkit/event/HandlerList;
	at com.denizenscript.depenizen.bukkit.events.mcmmo.mcMMOPlayerLevelChangeScriptEvent.destroy(mcMMOPlayerLevelChangeScriptEvent.java:86) ~[?:?]
	at net.aufdemrand.denizencore.events.ScriptEvent.reload(ScriptEvent.java:86) ~[?:?]
	at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:107) ~[?:?]
	at net.aufdemrand.denizen.Denizen$1.run(Denizen.java:895) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-edd0396-2a927e8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by Morphan1** [comment]
Good news! mcMMO broke this by forgetting a `getHandlerList` in `McMMOPlayerLevelChangeEvent`
https://github.com/mcMMO-Dev/mcMMO/commit/f7187410449c8deb6433fad6314a3d054c235dbd

**Comment by mcmonkey4eva** [comment]
Awaiting https://github.com/mcMMO-Dev/mcMMO/issues/3269

Also GG, mcMMO devs.

**Comment by t00thpick1** [comment]
GG

**Comment by SXRWahrheit** [comment]
lol nice to see you @t00thpick1

**Comment by mcmonkey4eva** [comment]
Should be fixed now
can you confirm @SXRWahrheit ?

**Comment by SXRWahrheit** [comment]
I think so, yeah. Will report back if the issue returns.

**Comment by mcmonkey4eva** [comment]
It's now actually fixed in Depenizen (previously the event had just been disabled pending the mcMMO update via https://github.com/DenizenScript/Depenizen/commit/65887f0232ea95df5a7b5e6ea62082876d734e22 ...)
