### ISSUE TITLE
New errors with 1.12.1 with bungeecord

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Depenizen#166]
Hey Morph, I updated to 1.12.1 today and now I am getting error like these in my proxy log and people can't connect. Any idea?

20:26:04 [WARNING] Error whilst handling query packet from null
java.lang.IllegalStateException: No session!
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:84)
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:517)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

1:42:01 [INFO] Disabling plugins
21:42:01 [INFO] §e+> [DepenizenPlugin] §fSocketServer stopped.
21:42:01 [INFO] Closing IO threads
21:42:01 [SEVERE] Exception in thread "Thread-9" 
21:42:01 [SEVERE] Exception in thread "Thread-8" 
21:42:01 [SEVERE] java.lang.NullPointerException
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.bungee.Settings.debugEnabled(Settings.java:14)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.bungee.dB.log(dB.java:21)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.bungee.DepenizenPlugin.debugMessage(DepenizenPlugin.java:101)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.common.socket.server.SocketServer.removeClient(SocketServer.java:130)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.common.socket.server.ClientConnection.run(ClientConnection.java:292)
21:42:01 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)
21:42:01 [SEVERE] java.lang.NullPointerException
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.bungee.Settings.debugEnabled(Settings.java:14)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.bungee.dB.log(dB.java:21)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.bungee.DepenizenPlugin.debugMessage(DepenizenPlugin.java:101)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.common.socket.server.SocketServer.removeClient(SocketServer.java:130)
21:42:01 [SEVERE] 	at com.denizenscript.depenizen.common.socket.server.ClientConnection.run(ClientConnection.java:292)
21:42:01 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)
21:42:06 [INFO] Using mbed TLS based native cipher.
21:42:06 [INFO] Using zlib based native compressor.
21:42:06 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:a1f9c2e:1258
21:42:06 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
21:42:06 [INFO] Epoll is working, utilising it!
21:42:06 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
21:42:06 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
21:42:06 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
21:42:06 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
21:42:06 [INFO] Discovered module: ModuleSpec(name

21:42:07 [SEVERE] Exception in thread "main" 
21:42:07 [SEVERE] java.io.IOException: Input/output error
21:42:07 [SEVERE] 	at java.io.FileInputStream.read0(Native Method)
21:42:07 [SEVERE] 	at java.io.FileInputStream.read(FileInputStream.java:207)
21:42:07 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
21:42:07 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
21:42:07 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
21:42:07 [SEVERE] 	at jline.internal.InputStreamReader.read(InputStreamReader.java:261)

**Comment by mcmonkey4eva** [comment]
First one looks like not-Depenizen, second one is post-shutdown, third is non-Depenizen...

**Comment by GomaTerzu** [comment]
Only using depenizen as a plugin for bungeecord. Any idea where the other two come from?

**Comment by mcmonkey4eva** [comment]
first is bungee itself, third is ??? cause it's not a complete error message...

**Comment by GomaTerzu** [comment]
Ok goign to check this later and post a new if it is still there
