### ISSUE TITLE
HyperConomy Not Loading Properly

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Depenizen#183]
So I've got both the current and latest versions of HyperConomy and Depenizen but it generates this error:
`[02:50:48] [Craft Scheduler Thread - 6/WARN]: [Depenizen] Plugin Depenizen v1.0.0 (build 389) generated an exception while executing task 70
java.lang.NoSuchMethodError: regalowl.hyperconomy.event.HyperEventHandler.registerListener(Ljava/lang/Object;)V
	at com.denizenscript.depenizen.bukkit.support.plugins.HyperConomySupport$1.run(HyperConomySupport.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-3d850ec-f46ccd7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by Elxafil** [comment]
@mcmonkey4eva are you going to fix this?

**Comment by mcmonkey4eva** [comment]
Why would I fix a Depenizen issue?
