### ISSUE TITLE
NoClassDefFoundError somewhere in Shopkeepers/Depenizen/Denizen interface

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Depenizen#205]
Spigot 1.12.2 latest
Shopkeepers 2.1.0-beta
Depenizen 1.0.0-b399
Denizen 1.0.2-b322
Citizens 2.0.22-b1547

After a recent Shopkeepers update, the following exception is generated on server restart. mcmonkey4eva [says](https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1776) it is a Depenizen issue. Please advise.

```
[18:06:36] [Server thread/WARN]: [Denizen] Task #96 for Denizen v1.0.2-SNAPSHOT (build 322) generated an exception
java.lang.NoClassDefFoundError: com/nisovin/shopkeepers/events/ShopkeeperTradeEvent
        at com.denizenscript.depenizen.bukkit.events.shopkeepers.ShopKeeperTradeScriptEvent.destroy(ShopKeeperTradeScriptEvent.java:73) ~[?:?]
        at net.aufdemrand.denizencore.events.ScriptEvent.reload(ScriptEvent.java:89) ~[?:?]
        at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:107) ~[?:?]
        at net.aufdemrand.denizen.Denizen$1.run(Denizen.java:912) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.nisovin.shopkeepers.events.ShopkeeperTradeEvent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        ... 11 more
```

**Comment by mcmonkey4eva** [comment]
Yeah so:
Depenizen links to Shopkeepers to add script tags/events/etc
Shopkeepers changed their API around in some arbitrary way in the update you downloaded
Depenizen now has to be updated to support whatever random change they made

This is one of the main reasons Depenizen is separated out from Denizen - all the plugins linked to by Depenizen continuously and randomly change their API layout for random silly reasons.

**Comment by SlimeDog** [comment]
Got it. Thanks. I imagine it was not entirely random, but it would be good if devs coordinated with Depenizen in such cases.

**Comment by mcmonkey4eva** [comment]
They (developers of plugins linked by Depenizen) shouldn't really need to coordinate with us or anyone else, so much as define and maintain a clear stable public API that won't be altered.
Most linking issues are either because an API was not maintained as stable, or there was no properly defined API and instead just a plugin's available public classes were used.
`com/nisovin/shopkeepers/events/ShopkeeperTradeEvent` is the missing Shopkeepers code path... which looks very much like an API that was just removed.

Glancing at the cause for that... it seems @blablubbabc made this commit: https://github.com/Shopkeepers/Shopkeepers/commit/522d187c6afeeb7ee14622220674e8db8633b4c0#diff-59e01f830fc320fac4ba4f427427c91d
Which just arbitrarily destroys all previous API links by just randomly inserting a required "`.api`" name in the middle of every single linkable API name.

**Comment by SlimeDog** [comment]
Nice.

**Comment by blablubbabc** [comment]
Sorry for causing the additional work. These changes are part of the process of moving away from using public classes as the public API, and instead define the API explicitly.
While the current API should still not be considered stable (I might continue arbitrarily moving things around as I see fit), the plan with these changes is to someday be able to provide a more stable and consistent public API. So I believe these changes will be worth it in the long run.

To ease the work of updating, I created a I PR for this: https://github.com/DenizenScript/Depenizen/pull/206

**Comment by mcmonkey4eva** [comment]
Thanks for making that PR @blablubbabc !  And thanks for pointing out the other thing to fix... there doesn't appear to be any matching API for getting the Entity properly in Shopkeepers? I've made a bit of a cheap but somewhat API-safe handler for that as a placeholder (in https://github.com/DenizenScript/Depenizen/commit/3162a0574129ba661befb1702a6c88a4e0f301f8 )

If you have or make a better way to achieve that please let me know (or PR it)!

Glad to hear you're working towards a proper stable API!

@SlimeDog Can you test / verify it's working (including any shopkeepers related scripts if you have any) in Depenizen build DEV-401+ ( http://ci.citizensnpcs.co/job/Depenizen/ )?

**Comment by blablubbabc** [comment]
> If you have or make a better way to achieve that please let me know (or PR it)!

Made some changes, so this should be easier to do with the next version of Shopkeepers: https://github.com/DenizenScript/Depenizen/pull/207
