### ISSUE TITLE
NSME with Denizen b329

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Depenizen#208]
Spigot 1.12.2 latest
Denizen 1.0.2-b329
Depenizen 1.0.0-b401

On startup:
```
[06:06:03] [Server thread/ERROR]: Error occurred while enabling Depenizen v1.0.0 (build 401) (Is it up to date?)
java.lang.NoSuchMethodError: net.aufdemrand.denizen.Denizen.getPropertyParser()Lnet/aufdemrand/denizencore/objects/properties/PropertyParser;
        at com.denizenscript.depenizen.bukkit.support.SupportManager.<init>(SupportManager.java:31) ~[?:?]
        at com.denizenscript.depenizen.bukkit.support.Supported.setup(Supported.java:27) ~[?:?]
        at com.denizenscript.depenizen.bukkit.DepenizenPlugin.checkPlugins(DepenizenPlugin.java:65) ~[?:?]
        at com.denizenscript.depenizen.bukkit.DepenizenPlugin.onEnable(DepenizenPlugin.java:27) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by mcmonkey4eva** [comment]
Why are you using dev builds but not in the Discord ( https://discord.gg/Q6pZGSR )?!

Current Denizen_Developmental builds are part of an experimental partial rewrite (thus there being 8 builds already today)

**Comment by SlimeDog** [comment]
Didn't know I was supposed to be in the Discord.

I usually use dev builds of everything, on my test servers, as a test. Apologies.

**Comment by SlimeDog** [comment]
Back to b325. Thanks.
