### ISSUE TITLE
Depenizen Error While Loading/Not Working

### ISSUE THREAD

**Issue by Velinquish** [DenizenScript/Depenizen#216]
I get this Depenizen error in console when loading it. I tried to use some of its tags but they apparently aren't valid.
```
[12:21:57] [Server thread/ERROR]: Error occurred while enabling Depenizen v1.0.0 (build 410) (Is it up to date?)
java.lang.IncompatibleClassChangeError: Expected static method net.aufdemrand.denizencore.objects.properties.PropertyParser.registerProperty(Ljava/lang/Class;Ljava/lang/Class;)V
	at com.denizenscript.depenizen.bukkit.support.SupportManager.register(SupportManager.java:47) ~[?:?]
	at com.denizenscript.depenizen.bukkit.support.Supported.set(Supported.java:51) ~[?:?]
	at com.denizenscript.depenizen.bukkit.support.Supported.setup(Supported.java:19) ~[?:?]
	at com.denizenscript.depenizen.bukkit.DepenizenPlugin.checkPlugins(DepenizenPlugin.java:65) ~[?:?]
	at com.denizenscript.depenizen.bukkit.DepenizenPlugin.onEnable(DepenizenPlugin.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by mcmonkey4eva** [comment]
Update Depenizen and Denizen to latest from jenkins

**Comment by Velinquish** [comment]
I've done that. I'm now using Denizen 1.0.2-Snapshot Build 295 and Depenizen 1 Build 410 (the same build as before). The error message seems to be identical and the tags still don't seem to work.

**Comment by mcmonkey4eva** [comment]
Denizen build 295 is not a valid current build.
Grab latest from http://ci.citizensnpcs.co/job/Denizen/

**Comment by Velinquish** [comment]
I used the latest from there, build 1651, but when I used /denizen version, it told me it was 1.0.2-Snapshot (Build 295).
