### ISSUE TITLE
Disguise Command Error

### ISSUE THREAD

**Issue by Velinquish** [DenizenScript/Depenizen#217]
I used Depenizen to disguise a NPC as an ender crystal but when I logged out and logged back in, it removed the disguise and gave an error in console about the health trait that I had attached to the NPC. This is the error message:
```
[14:52:19] [Server thread/ERROR]: [Citizens] An exception occurred while the trait health was spawning for NPC ID 530.
[14:52:19] [Server thread/WARN]: java.lang.ClassCastException: net.citizensnpcs.npc.entity.nonliving.EnderCrystalController$EnderCrystalNPC cannot be cast to org.bukkit.entity.LivingEntity
[14:52:19] [Server thread/WARN]: 	at net.aufdemrand.denizen.npc.traits.HealthTrait.setHealth(HealthTrait.java:235)
[14:52:19] [Server thread/WARN]: 	at net.aufdemrand.denizen.npc.traits.HealthTrait.onSpawn(HealthTrait.java:157)
[14:52:19] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:244)
[14:52:19] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.spawn(EventListen.java:542)
[14:52:19] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:519)
[14:52:19] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:135)
[14:52:19] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
[14:52:19] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:52:19] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:55)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[14:52:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34)
[14:52:19] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:745)
[14:52:19] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[14:52:19] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[14:52:19] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[14:52:19] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```
Is there any way I can permanently keep the NPC disguised as an ender crystal and have it still retain its ability to take damage?

**Comment by mcmonkey4eva** [comment]
Update your server.
Run latest plugins and a version more recent than freakin 1.9 (1.12.2 is ideal for the moment)

**Comment by mcmonkey4eva** [comment]
Also it looks a lot like you turned an NPC into a crystal, not disguised it.

**Comment by Velinquish** [comment]
This was the code I used for it: `disguise misc type:ender_crystal target:<npc>`

**Comment by Mwthorn** [comment]
The disguise plugin's intentions were to only be used on normal entities such as mobs and players.
The correct way to disguise an NPC should be `/npc type (entity)`

**Comment by Velinquish** [comment]
I think `/npc type <entity>` changes the type entirely. When I set the type from an attack-able entity like a zombie to an ender crystal, it can't take damage anymore. I only want it to _look_ like an ender crystal.

**Comment by mcmonkey4eva** [comment]
@Velinquish can you please update your server to 1.12.2 or 1.13.2 with fully up-to-date plugins and post the error message as received by the updated server (if it's still present).
