### ISSUE TITLE
IllegalArgumentException on player connect

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Depenizen#225]
Spigot 1.13.1 latest
Citizens version 2.0.24-b1568
Denizen version 1.0.3-b411
Depenizen 1.0.0-b414

This occurs every time I connect.
```
[08:53:47 WARN]: [Depenizen] Task #666 for Depenizen v1.0.0 (build 414) generated an exception
java.lang.IllegalArgumentException: Channel must contain : separator
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.plugin.messaging.StandardMessenger.isOutgoingChannelRegistered(StandardMessenger.java:401) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:514) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1213) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at com.denizenscript.depenizen.bukkit.support.clientizen.ClientizenSupport.send(ClientizenSupport.java:232) ~[?:?]
        at com.denizenscript.depenizen.bukkit.support.clientizen.ClientizenSupport.access$000(ClientizenSupport.java:33) ~[?:?]
        at com.denizenscript.depenizen.bukkit.support.clientizen.ClientizenSupport$1.run(ClientizenSupport.java:140) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by mcmonkey4eva** [comment]
Thanks! I guess I missed more instances of that change being needed for 1.13 when I fixed it the first time.
New commit pushed,
Should be fixed in Depenizen build 415

**Comment by SlimeDog** [comment]
No worries. Appreciate fast response.

Verified no longer an issue with build 415.
