### ISSUE TITLE
Depenizen in red - 1.13

### ISSUE THREAD

**Issue by 21stCheran** [DenizenScript/Depenizen#231]
[19:54:30] [Server thread/INFO]: [Depenizen] Loading Depenizen v1.0.0 (build 420)
[19:54:52] [Server thread/INFO]: [Depenizen] Enabling Depenizen v1.0.0 (build 420)*
[19:54:52] [Server thread/ERROR]: Error occurred while enabling Depenizen v1.0.0 (build 420) (Is it up to date?)
java.lang.NoClassDefFoundError: com/denizenscript/depenizen/common/Depenizen
	at com.denizenscript.depenizen.bukkit.DepenizenPlugin.onEnable(DepenizenPlugin.java:24) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.denizenscript.depenizen.common.Depenizen
[19:54:52] [Server thread/INFO]: [Depenizen] Disabling Depenizen v1.0.0 (build 420)
[19:54:52] [Server thread/ERROR]: Error occurred while disabling Depenizen v1.0.0 (build 420) (Is it up to date?)
java.lang.NoClassDefFoundError: com/denizenscript/depenizen/bukkit/support/bungee/BungeeSupport
	at com.denizenscript.depenizen.bukkit.DepenizenPlugin.onDisable(DepenizenPlugin.java:32) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.denizenscript.depenizen.bukkit.support.bungee.BungeeSupport

**Comment by mcmonkey4eva** [comment]
Looks like either a missed error (some error occurred earlier in your logs, and is the actual error) or a corrupt jar copy (in which case, just redownload it).
If you find the source error in your logs, please reply with that error in full.
