### ISSUE TITLE
on mythicmobs span for Spawners

### ISSUE THREAD

**Issue by bushuaichen** [DenizenScript/Depenizen#268]
[21:54:44] [Server thread/WARN]: java.lang.IllegalArgumentException: No serializer found for class com.google.common.base.Absent
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:940)
[21:54:44] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager.createDataWatcher(PacketsManager.java:504)
[21:54:44] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager.constructSpawnPackets(PacketsManager.java:429)
[21:54:44] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:918)
[21:54:44] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[21:54:44] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143)
[21:54:44] [Server thread/WARN]: 	at net.aufdemrand.denizen.nms.impl.packets.handlers.DenizenNetworkManager_v1_12_R1.sendPacket(DenizenNetworkManager_v1_12_R1.java:282)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1142)
[21:54:44] [Server thread/WARN]: 	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.sendPacket(AbstractListenerPlayIn_v1_12_R1.java:50)
[21:54:44] [Server thread/WARN]: 	at net.aufdemrand.denizen.nms.impl.packets.handlers.DenizenPacketListener_v1_12_R1.sendPacket(DenizenPacketListener_v1_12_R1.java:47)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:344)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:449)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:77)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityTracker.updatePlayers(EntityTracker.java:182)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:834)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:54:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:54:44] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
Your title makes no sense and your error message has no relation to Depenizen at all.
