### ISSUE TITLE
NoSuchFieldError: additionalDebugLines

### ISSUE THREAD

**Issue by ChrissW-R1** [DenizenScript/Depenizen#379]
Since version 2.0.0 (build 778) we get the following error on enabling the plugin:

```
[18:11:59] [Server thread/ERROR]: Error occurred while enabling Depenizen v2.0.0 (build 780) (Is it up to date?)
java.lang.NoSuchFieldError: additionalDebugLines
	at com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:43) ~[Depenizen-2.0.0-b780.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:11:59] [Server thread/INFO]: [Depenizen] Disabling Depenizen v2.0.0 (build 780)
```

With version 2.0.0 (build 777) everything is fine.

**Comment by mcmonkey4eva** [comment]
support is on discord @ https://discord.gg/Q6pZGSR
