### ISSUE TITLE
Depenizen does not support FactionsUUID and fails to load

### ISSUE THREAD

**Issue by Roos-Skywalker** [DenizenScript/Depenizen#380]
There are no modern official builds for Factions, which is why I use FactionsUUID (paid). It is the most bug free and actively developed fork. I gladly provide a sample for debugging.

**Versions**
- Spigot: purpur-1.18.2-1632
- Citizens 2.0.30 BUILD 6.2
- Sentinel 2.6.0
- Depenizen-2.0.0-b780
- FactionsUUID 1.6.9.5-U0.6.12-b290

**Error**
[13:19:11] [Server thread/INFO]: [Sentinel] Enabling Sentinel v2.6.0-SNAPSHOT (build 472)
[13:19:11] [Server thread/INFO]: [Sentinel] Sentinel loading...
[13:19:11] [Server thread/INFO]: [Sentinel] Running on java version: 18.0.1.1
[13:19:11] [Server thread/INFO]: [Sentinel] Sentinel loaded on a fully supported Minecraft version. If you encounter any issues or need to ask a question, please join our Discord at https://discord.gg/Q6pZGSR and post in the '#sentinel' channel.
[13:19:11] [Server thread/INFO]: [Sentinel] Vault linked! Group targets will work.
[13:19:11] [Server thread/WARN]: [Sentinel] You are running an unsupported fork of Factions that has listed itself as Factions. Sentinel will not load the integration for it. Please inform the developer of your Factions fork to set the plugin name and classpath to their own plugin, to avoid issues with plugins built for the official version of Factions.
[13:19:11] [Server thread/INFO]: [Sentinel] Sentinel found WorldGuard! Adding support for it!
[13:19:11] [Server thread/INFO]: [Sentinel] Sentinel loaded!
[13:19:11] [Server thread/INFO]: [Factions] Disregarding any whining from Sentinel and trying to integrate anyway!
[13:19:11] [Server thread/INFO]: [Factions] Loaded Sentinel integration!
[13:19:11] [Server thread/INFO]: [Depenizen] Enabling Depenizen v2.0.0 (build 780)
[13:19:11] [Server thread/INFO]: +> [Depenizen] Depenizen loading... 
[13:19:11] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'LuckPerms'! 
[13:19:11] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'WorldEdit'! 
[13:19:11] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'Essentials'! 
[13:19:11] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'Jobs'! 
[13:19:11] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'WorldGuard'! 
[13:19:11] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'LibsDisguises'! 
[13:19:12] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'Sentinel'! 
[13:19:12] [Server thread/INFO]:  ERROR!
                 Error Message: Cannot load Depenizen bridge for 'Factions': Only official modern Factions versions are supported. 
[13:19:12] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'mcMMO'! 
[13:19:12] [Server thread/INFO]: +> [Depenizen] Loaded bridge for 'ViaVersion'! 
[13:19:12] [Server thread/ERROR]: Error occurred while enabling Depenizen v2.0.0 (build 780) (Is it up to date?)
java.lang.NoSuchFieldError: additionalDebugLines
	at com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:43) ~[Depenizen-2.0.0-b780.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:19:12] [Server thread/INFO]: [Depenizen] Disabling Depenizen v2.0.0 (build 780)
[13:19:12] [Server thread/INFO]: [Denizen]  v1.2.5-SNAPSHOT (build 1772-REL) disabled.

[Also created an issue at FactionsUUID.](https://github.com/drtshock/Factions/issues/1445)

**Comment by mcmonkey4eva** [comment]
A: Depenizen supports the official version of Factions, and not incompatible forks.
B: Depenizen only supports free plugins. "Premium" plugins both _can not_ (for legal reasons) and _will not_ (for moral reasons) be supported.

**Comment by Roos-Skywalker** [comment]
Thank you for your time to respond. I hope you have a nice day. :)
